services:
  express:
    image: concierge-api
    env_file: .env
    build:
      context: .
    expose:
      - "3000"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - nginx-express
      - mongo-express
    depends_on:
      - mongo

  nginx:
    image: nginx:1.27-alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - express
    networks:
      - nginx-express

  mongo:
    image: mongo:6
    restart: always
    env_file: .env
    ports:
      - "27017:27017"
    networks:
      - mongo-express
    volumes:
      - mongo:/data/db

networks:
  nginx-express:
  mongo-express:

volumes:
  mongo:
